- name: Backup Docker containers mount points
  hosts: vms
  gather_facts: false

  tasks:

    - name: Create a directory to store the containers backup
      ansible.builtin.file:
        path: /mnt/backup_library/{{ name }} # retrieve the inventory variable for executing host
        state: directory
        mode: '0700'
        owner: "{{ uid }}"
        group: "{{ gid }}"
      become: true

    - name: Checks for Jenkins directory
      ansible.builtin.stat:
        path: /opt/jenkins
      register: jenkins

    - name: Jenkins
      ansible.builtin.copy:
        src: /opt/jenkins # does not end with "/", the directory itself with all contents is copied
        dest: /mnt/backup_library/{{ name }}/
        remote_src: yes # the source is on remote host
        mode: preserve
        directory_mode: preserve
        force: true # Influence whether the remote file must always be replaced.
      when: jenkins.stat.isdir is defined and jenkins.stat.isdir