- name: Configure DEV Server backup share
  hosts: controller
  gather_facts: false

  tasks:

    - name: Install CIFS Utils
      ansible.builtin.yum:
        name:
          - cifs-utils
        state: latest
        update_cache: true
      become: true

    - name: Create a directory to store credentials
      ansible.builtin.file:
        path: "/opt/vault"
        state: directory
        mode: '0700'
        owner: "{{ uid }}"
        group: "{{ gid }}"
      become: true # elevate because is inside opt

    - name: Create a credentials file for samba share access
      ansible.builtin.copy:
        dest: /opt/vault/.smbcredentials
        content: |
          username={{ lookup('env', 'nas_share_user') }}
          password={{ lookup('env', 'nas_share_password') }}
          domain=WORKGROUP
        mode: '0600'

    - name: Mount SMB volume and change fstab file
      ansible.posix.mount:
        src: "{{ lookup('env', 'kopia_backup_share') }}/{{ kopia_destination_dir }}" # URL in the form //X.X.X.X/FOLDER
        path: "/mnt/{{ kopia_destination_dir }}" # VM specific path
        opts: "credentials=/opt/vault/.smbcredentials,uid={{ uid }},gid={{ gid }},x-systemd.automount"
        fstype: cifs
        state: mounted
      become: true