---

services:

  semaphore_mysql:
    image: docker.io/library/mysql:latest
    hostname: semaphore_mysql
    container_name: semaphore_mysql
    volumes:
      - /opt/semaphore/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=semaphore_db
      - MYSQL_USER=semaphore
      - MYSQL_PASSWORD=secret-password  # change!
    networks:
      - semaphore-network
    restart: unless-stopped

  semaphore:
    container_name: semaphore
    image: docker.io/semaphoreui/semaphore:latest
    ports:
      - 3000:3000
    environment:
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=secret-password  # change!
      - SEMAPHORE_DB_HOST=semaphore_mysql
      - SEMAPHORE_DB_PORT=3306
      - SEMAPHORE_DB_DIALECT=mysql
      - SEMAPHORE_DB=semaphore_db
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=secret-admin-password  # change!
      - SEMAPHORE_ADMIN_NAME=admin
      - SEMAPHORE_ADMIN_EMAIL=admin@localhost
      - SEMAPHORE_ADMIN=admin
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=${encryption_key}  # add to your access key encryption !
      - ANSIBLE_HOST_KEY_CHECKING=false  # (optional) change to true if you want to enable host key checking
      - TZ=America/Sao_Paulo
    #volumes:
    #  - /opt/semaphore/inventory/:/inventory
    #  - /opt/semaphore/authorized-keys/:/authorized-keys
    #  - /opt/semaphore/config/:/etc/semaphore
    networks:
      - semaphore-network
    user: root
    restart: unless-stopped
    depends_on:
      - semaphore_mysql

networks:
  semaphore-network: