---

services:

  semaphore_mysql:
    image: docker.io/library/mysql:latest
    hostname: semaphore_mysql
    container_name: semaphore_mysql
    volumes:
      - /opt/semaphore/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=semaphore_db
      - MYSQL_USER=semaphore
      - MYSQL_PASSWORD=${mysql_password} # add environment variable
    networks:
      - sm_network
    restart: unless-stopped

  semaphore:
    container_name: semaphore
    image: docker.io/semaphoreui/semaphore:latest
    ports:
      - 3000:3000
    environment:
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=${mysql_password} # add environment variable
      - SEMAPHORE_DB_HOST=semaphore_mysql
      - SEMAPHORE_DB_PORT=3306
      - SEMAPHORE_DB_DIALECT=mysql
      - SEMAPHORE_DB=semaphore_db
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=${admin_password} # add environment variable
      - SEMAPHORE_ADMIN_NAME=admin
      - SEMAPHORE_ADMIN_EMAIL=admin@localhost
      - SEMAPHORE_ADMIN=admin
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=${encryption_key}  # generate with command: head -c32 /dev/urandom | base64
      - ANSIBLE_HOST_KEY_CHECKING=false  # (optional) change to true if you want to enable host key checking
      - TZ=America/Sao_Paulo
    labels:
      - "com.centurylinklabs.watchtower.enable: true"
    volumes:
      - /opt/semaphore/config:/etc/semaphore
      - /opt/semaphore/data:/var/lib/semaphore
      - /opt/semaphore/tmp:/tmp/semaphore
    networks:
      - sm_network
    user: root
    restart: unless-stopped
    depends_on:
      - semaphore_mysql

networks:
  sm_network: