
- name: Install Apache Maven
  gather_facts: false
  hosts: nodes
  become: true

  tasks:

    - name: Install Apache Maven
      ansible.builtin.yum:
        name:
          - maven
        state: absent
        update_cache: true
