
- name: Install Apache Maven
  gather_facts: false
  hosts: controller
  become: true

  tasks:

    - name: Install package
      ansible.builtin.yum:
        name:
          - maven
        state: latest
        update_cache: true
