---
- name: Install docker community edition
  gather_facts: false
  hosts: vms
  become: true

  tasks:

    - name: Install YUM utils
      ansible.builtin.yum:
        name:
          - yum-utils
        state: latest
        update_cache: true

    - name: Add Docker repository
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Ensure "docker" group exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add SSH user to docker group
      ansible.builtin.user:
        name: "{{ lookup('ansible.builtin.env', 'ssh_user') }}"
        groups: docker
        append: yes

    - name: Create the daemon file to enable metrics endpoint
      ansible.builtin.lineinfile:
        path: "/etc/docker/daemon.json"
        state: present
        create: true
        regexp: '{ "metrics-addr": "0.0.0.0:9323" }'
        line: '{ "metrics-addr": "0.0.0.0:9323" }'

    - name: Allow traffic in default zone on port 9323/tcp for metrics endpoint
      ansible.posix.firewalld:
        port: 9323/tcp
        permanent: true
        state: enabled

    - name: Reload firewalld service
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      become: true # should be run as root

    # Update Docker service to expose the API to let Jenkins create agents on demand
    - name: Ensure the docker.service file exists
      ansible.builtin.stat:
        path: /lib/systemd/system/docker.service
      register: docker_service_file

    - name: Backup the existing docker.service file
      ansible.builtin.copy:
        src: /lib/systemd/system/docker.service
        dest: /lib/systemd/system/docker.service.bak
        remote_src: yes
      when: docker_service_file.stat.exists

    - name: Update the ExecStart line in the docker.service file
      ansible.builtin.lineinfile:
        path: /lib/systemd/system/docker.service
        regexp: '^ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock'
        line: 'ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock'
        backup: yes

    - name: Reload the systemd daemon
      ansible.builtin.command: systemctl daemon-reload

    - name: Restart the Docker service
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Verify Docker is listening on the TCP port
      ansible.builtin.command: ss -tln | grep 4243
      register: tcp_check
      ignore_errors: true

    - name: Debug output of TCP port check
      ansible.builtin.debug:
        msg: "{{ tcp_check.stdout }}"