
- name: Install Java latest JDK release
  gather_facts: false
  hosts: controller
  become: true

  tasks:

    - name: Install package
      ansible.builtin.yum:
        name:
          - java-latest-openjdk-devel
        state: latest
        update_cache: true
