---
- name: Deploy Prometheus latest
  hosts: controller
  gather_facts: false

  tasks:

    - name: Ensure the monitoring network is created
      community.docker.docker_network:
        name: monitoring_network
        state: present

    - name: Create a directory to map Prometheus config
      ansible.builtin.file:
        path: /opt/prometheus/config
        state: directory
        mode: '0700'
        owner: "{{ uid }}"
        group: "{{ gid }}"
      become: true # elevate because is inside opt

    - name: Create a directory to map Prometheus data
      ansible.builtin.file:
        path: /opt/prometheus/data
        state: directory
        mode: '0700'
        owner: "{{ uid }}"
        group: "{{ gid }}"
      become: true # elevate because is inside opt

    - name: Deploy Prometheus
      community.docker.docker_container:
        name: prometheus
        image: "prom/prometheus:latest"
        ports:
          - "9090:9090"
        volumes:
          - /opt/prometheus/config:/etc/prometheus # map the configuration file
          - /opt/prometheus/data:/prometheus
        networks:
          - name: monitoring_network
        user: "{{ uid }}:{{ gid }}"
        restart_policy: unless-stopped
        state: started