---
- name: Deploy Grafana latest
  hosts: controller
  gather_facts: false

  tasks:

    - name: Ensure the monitoring network is created
      community.docker.docker_network:
        name: monitoring_network
        state: present

    - name: Create a directory to map Grafana information
      ansible.builtin.file:
        path: /opt/grafana
        state: directory
        mode: '0700'
        owner: "{{ lookup('ansible.builtin.env', 'ssh_uid') }}"
        group: "{{ lookup('ansible.builtin.env', 'ssh_gid') }}"
      become: true # elevate because is inside opt

    - name: Deploy Grafana
      community.docker.docker_container:
        name: grafana
        image: grafana/grafana:latest
        ports:
          - "3001:3000"
        volumes:
          - grafana_data:/etc/grafana/
        networks:
          - name: monitoring_network
        user: "{{ lookup('ansible.builtin.env', 'ssh_uid') }}:{{ lookup('ansible.builtin.env', 'ssh_gid') }}"
        restart_policy: unless-stopped
        state: started