---
- name: Deploy Jenkins Agent as Docker container
  hosts: nodes
  gather_facts: false

  tasks:

    - name: Ensure the devops network is created
      community.docker.docker_network:
        name: devops_network
        state: present

    - name: Deploy Jenkins Agent
      community.docker.docker_container:
        name: jenkins_agent
        image: jenkins/ssh-agent:latest-jdk21
        ports:
          - "4422:22"
        env:
          JENKINS_AGENT_SSH_PUBKEY: "{{ lookup('ansible.builtin.env', 'jenkins_controller_ssh_key') }}"
        networks:
          - name: devops_network
        user: root
        restart_policy: unless-stopped
        state: started