---
- name: Deploy Jenkins Agent as Docker container
  hosts: nodes
  gather_facts: false

  tasks:

    - name: Create a directory to map Jenkins Agent information
      ansible.builtin.file:
        path: /opt/jenkins/agent
        state: directory
        mode: '0700'
        owner: "{{ uid }}"
        group: "{{ gid }}"
      become: true # elevate because is inside opt

    - name: Ensure the devops network is created
      community.docker.docker_network:
        name: devops_network
        state: present

    - name: Deploy Jenkins Agent
      community.docker.docker_container:
        name: jenkins_agent
        image: jenkins/ssh-agent:latest-jdk21
        command: apt-get install -qy maven
        ports:
          - "4422:22"
        volumes:
          - /opt/jenkins/agent:/home/jenkins/agent
          - /var/run/docker.sock:/var/run/docker.sock
        env:
          JENKINS_AGENT_SSH_PUBKEY: "{{ lookup('ansible.builtin.env', 'jenkins_controller_ssh_key') }}"
        networks:
          - name: devops_network
        #user: "{{ uid }}:{{ gid }}"
        restart_policy: unless-stopped
        state: started