---
- name: Deploy portainer-ce latest
  hosts: controller
  gather_facts: false

  tasks:

    - name: Create new volume
      community.docker.docker_volume:
        name: portainer-data

    - name: Create a directory to map Portainer information
      ansible.builtin.file:
        path: /opt/portainer
        state: directory
        mode: '0700'
        owner: "{{ uid }}"
        group: "{{ gid }}"
      become: true # elevate because is inside opt

    - name: Deploy portainer
      community.docker.docker_container:
        name: portainer
        image: "portainer/portainer-ce:latest"
        ports:
          - "9443:9443"
        volumes:
          - /run/docker.sock:/var/run/docker.sock
          - /opt/portainer:/data
        user: "{{ uid }}:{{ gid }}"
        restart_policy: unless-stopped