- name: Deploy Open Project
  hosts: controller
  gather_facts: false

  vars:

    openproject_container_name: openproject
    openproject_image: openproject/community:13-slim
    postgres_container_name: openproject_postgres
    postgres_image: postgres:latest

    # Volume mapping
    openproject_assets_dir: /opt/openproject/assets
    openproject_database_dir: /opt/openproject/database

  tasks:

    - name: Ensure the network is created
      community.docker.docker_network:
        name: openproject_network
        state: present

    - name: Create a directory to map Docker volumes
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0700'
        owner: "{{ uid }}"
        group: "{{ gid }}"
      loop:
        - "{{ openproject_assets_dir }}"
        - "{{ openproject_database_dir }}"
      become: true # elevate because is inside opt

    - name: Stop and remove the existing OpenProject containers if it exists
      community.docker.docker_container:
        name: "{{ openproject_container_name }}"
        state: absent
      loop:
        - "{{ postgres_container_name }}"
        - "{{ openproject_container_name }}"

    - name: Remove the existing OpenProject image if it exists
      community.docker.docker_image:
        name: "{{ openproject_image }}"
        source: local
        state: absent

    - name: Pull the latest Docker images
      community.docker.docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - "{{ openproject_image }}"
        - "{{ postgres_image }}"

    - name: Deploy PostgreSQL container
      community.docker.docker_container:
        name: "{{ postgres_container_name }}"
        hostname: openproject_postgres
        image: "{{ postgres_image }}"
        networks:
          - name: openproject_network
        env:
          POSTGRES_USER: openproject
          POSTGRES_PASSWORD: "{{ lookup('env', 'openproject_db_password') }}"
          POSTGRES_DB: openproject_db
        volumes:
          - "{{ openproject_database_dir }}:/var/lib/postgresql/data"
        state: started

    - name: Deploy OpenProject
      community.docker.docker_container:
        name: "{{ openproject_container_name }}"
        image: "{{ openproject_image }}"
        ports:
          - "8081:80"
        env:
          SECRET_KEY_BASE: "{{ lookup('env', 'openproject_secret_key') }}"
          OPENPROJECT_DB_URL: "postgresql://openproject_postgres:5432/openproject_db"
          OPENPROJECT_HOST__NAME: "{{ lookup('env', 'openproject_domain') }}"
          OPENPROJECT_HTTPS: "false"
          OPENPROJECT_DB_USERNAME: openproject
          OPENPROJECT_DB_PASSWORD: "{{ lookup('env', 'openproject_db_password') }}"
        volumes:
          - "{{ openproject_assets_dir }}:/var/openproject/assets"
        networks:
          - name: openproject_network
        restart_policy: unless-stopped
        state: started

    